### ISSUE TITLE
SOLR available from docker?

### ISSUE THREAD

**Issue by stuchalk** [MaastrichtUniversity/ols-docker#2]
I have install this and its working great.  Is there access to the SOLR index directly via the Docker container?

**Comment by danieltheunissen** [comment]
There are two seperate methods to get direct access to the SOLR index.

1.  From within the docker container 
`docker exec -it <name_of_container> bash `
`apt-get install curl `
`curl "http://localhost:8983/solr/ontology/select?q=label:human" `
2. Open the SOLR index for access outside the docker container.
Edit the Dockerfile and change **EXPOSE 8080** into **EXPOSE 8080 8983**
If ols docker is already running stop it
`docker build -t ols .`
`docker run -d -p 8080:8080  -p 8983:8983 -t ols`
`curl "http://<server_name>:8983/solr/ontology/select?q=label:human"`
Or with a browser goto  http://<server_name>:8983 for solr web interface
